from typing import List, Dict, Any, Optional
from pydantic import BaseModel


class CharacterFacts(BaseModel):
    name: Optional[str] = None
    gender: Optional[str] = None
    current_emotion: str
    relationship_with_user: Optional[str] = None
    newly_discovered_facts: Optional[str] = None
    main_topic_of_current_conversation: Optional[str] = None

class CharacterJsonResponse(BaseModel):
    message: str
    character_facts: CharacterFacts

    @classmethod
    def json_schema(cls) -> Dict[str, Any]:
        return {
            "type": "json_schema",
            "json_schema": {
                "name": "character_json_response",
                "strict": True,
                "schema": {
                    "type": "object",
                    "properties": {
                        "message": {
                            "type": "string",
                            "description": "a message that is generated by the character built by the user"
                        },
                        "character_facts": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "type": "string",
                                    "description": "캐릭터 이름"
                                },
                                "gender": {
                                    "type": "string",
                                    "description": "캐릭터의 성별"
                                },
                                "relationship_with_user": {
                                    "type": "string",
                                    "description": "캐릭터와 유저의 현재 관계"
                                },
                                "current_emotion": {
                                    "type": "string",
                                    "description": "현재 캐릭터가 느끼는 감정 상태. (happy, sad, angry, surprised, neutral, flustered) 항목 중 하나를 선택. 적합한 항목이 없다면 neutral을 선택."
                                },
                                "newly_discovered_facts": {
                                    "type": "string",
                                    "description": "유저와의 최근 대화에서 새롭게 (정의,획인,합의)된 캐릭터에 대한 사실을 서술형으로 요약한 문장"
                                },
                                "main_topic_of_current_conversation": {
                                    "type": "string",
                                    "description": "유저와의 캐릭터가 나누고 있는 현재 대화에서 주요 주제"
                                }
                            },
                            "required": ["current_emotion"]
                        }
                    },
                    "required": ["message", "facts"]
                }
            }
        }


class CharacterResponse(BaseModel):
    name: str
    #attendee_id: Optional[int] = None
    is_main_character: bool
    is_storyteller: bool
    message: str

class AIResponse(BaseModel):
    messages: List[CharacterResponse]
    summary: str

    @classmethod
    def json_schema(cls) -> Dict[str, Any]:
        return {
            "type": "json_schema",
            "json_schema": {
                "name": "ai_response",
                "strict": True,
                "schema": {
                    "type": "object",
                    "properties": {
                        "messages": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string",
                                        "description": "캐릭터의 이름"
                                    },
                                    "is_main_character": {
                                        "type": "boolean",
                                        "description": "주인공 여부"
                                    },
                                    "is_storyteller": {
                                        "type": "boolean",
                                        "description": "내레이터 여부"
                                    },
                                    "message": {
                                        "type": "string",
                                        "description": "캐릭터의 메시지"
                                    }
                                },
                                "required": ["name", "is_main_character", "is_storyteller", "message"]
                            }
                        },
                        "summary": {
                            "type": "string",
                            "description": "대화 요약"
                        }
                    },
                    "required": ["messages", "summary"]
                }
            }
        }